# Neural Net
정의

## 퍼셉트론(Perceptron)
퍼셉트론은 다수의 신호를 input(입력)으로 받아 하나의 output(출력)을 반환한다.

아래의 예시는 input(입력)이 2개인 퍼셉트론이다.

<img src="img/NN_A_01.PNG">

아주 기본적인 퍼셉트론은 뉴런에서 보내온 신호의 총합이 정해진 한계(임계값; $\theta$)를 넘어설 때만 1을 출력한다. (즉, 뉴런이 활성화되는 경우에만!)



따라서 이 구조를 수식으로 표현하면 아래와 같다.

$$  y = 0 \ \ \ \ (w_1x_1 + w_2x_2 \leq \theta) $$
$$  y = 1 \ \ \ \ (w_1x_1 + w_2x_2 > \theta) $$

### 논리회로 (AND, NAND, OR, XOR)

입력(input)과 출력(output)의 대응 표를 진리표(truth table)라고 한다.

각 게이트 별 진리표는 다음과 같다.

#### AND 게이트

<img src="img/NN_A_02.PNG">

AND 게이트는 두 입력이 모두 1인 경우에만 1을 출력하고 나머지는 0을 출력한다.

In [69]:
import numpy as np

def AND(elem_matrix):
    w1 = np.ones((1,1)) * 0.5
    w2 = np.ones((1,1)) * 0.5
    w = np.concatenate((w1,w2))
    
    theta = np.ones((4,1)) * 0.7
    
    cal_result = (np.dot(elem_matrix.T, w) > theta).astype(int)
    return cal_result

elem_input = np.array([[0,1,0,1],
                       [0,0,1,1]])

print(elem_input.T,'에 대한 AND게이트의 결과는...','\n')
print(AND(elem_input))

[[0 0]
 [1 0]
 [0 1]
 [1 1]] 에 대한 AND게이트의 결과는... 

[[0]
 [0]
 [0]
 [1]]


#### NAND 게이트

<img src="img/NN_A_03.PNG">

In [71]:
import numpy as np

def NAND(elem_matrix):
    w1 = np.ones((1,1)) * -0.5 # AND와 부호를 반대로 하여 가중치를 부여한다.
    w2 = np.ones((1,1)) * -0.5 # AND와 부호를 반대로 하여 가중치를 부여한다.
    w = np.concatenate((w1,w2))
    
    b = np.ones((4,1)) * 0.7 # Bias; 편향
    
    theta = np.ones((4,1)) * 0
    
    cal_result = (np.dot(elem_matrix.T, w) + b > theta).astype(int)
    return cal_result

elem_input = np.array([[0,1,0,1],
                       [0,0,1,1]])

print(elem_input.T,'에 대한 NAND게이트의 결과는...','\n')
print(NAND(elem_input))

[[0 0]
 [1 0]
 [0 1]
 [1 1]] 에 대한 NAND게이트의 결과는... 

[[1]
 [1]
 [1]
 [0]]


#### OR 게이트

<img src="img/NN_A_04.PNG">

In [73]:
import numpy as np

def OR(elem_matrix):
    w1 = np.ones((1,1)) * 0.2 # AND와 부호를 반대로 하여 가중치를 부여한다.
    w2 = np.ones((1,1)) * 0.2 # AND와 부호를 반대로 하여 가중치를 부여한다.
    w = np.concatenate((w1,w2))
    
    b = np.ones((4,1)) * -0.2 # Bias; 편향
    
    theta = np.ones((4,1)) * 0
    
    cal_result = (np.dot(elem_matrix.T, w) + b <= theta).astype(int)
    return cal_result

elem_input = np.array([[0,1,0,1],
                       [0,0,1,1]])

print(elem_input.T,'에 대한 OR게이트의 결과는...','\n')
print(OR(elem_input))

[[0 0]
 [1 0]
 [0 1]
 [1 1]] 에 대한 OR게이트의 결과는... 

[[1]
 [1]
 [1]
 [0]]


#### XOR 게이트

<img src="img/NN_A_05.PNG">

XOR 게이트(배타적 논리합 논리회로)는 $x_1$과 $x_2$ 중 한쪽이 1일 때만 1을 출력한다.

<b>따라서 <span style="color:red">기본적인 퍼셉트론으로는 XOR 게이트를 구현하는 것이 불가능하다.</span></b>

이유는 아래와 같다.

<img src="img/NN_A_06.PNG">

퍼셉트론을 구현한 코드를 살펴보면 알겠지만 AND, NAND, OR 게이트는 가중치와 편향만 다르게 부여한 같은 구조의 일차방정식인 것을 알 수 있다.